# Generated by Django 5.1 on 2024-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeentry',
            name='author',
        ),
    ]
